version: '3.1'

services:
  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
      DISABLE_AUTH: "false"

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"

  email-service:
    build: ./email-service
    environment:
      MICRO_REGISTRY: "mdns"

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"

  # Usage: https://micro.mu/reference#api
  shippy-api:
    image: "micro/micro:v1.18.0"
    ports:
      - 8080:8080
    command: "api --handler=rpc --address=:8080 --namespace=shippy"
    environment:
      MICRO_REGISTRY: "mdns"